* FLAC Support
git-svn-id: svn://svn.code.sf.net/p/gmerlin/code/trunk@80 214d8ac5-8513-4f59-80f8-2f39b674a24a

diff --git a/gmerlin_avdecoder/configure.in b/gmerlin_avdecoder/configure.in
--- a/gmerlin_avdecoder/configure.in
+++ b/gmerlin_avdecoder/configure.in
@@ -169,6 +169,62 @@ if test x$have_faad2 = xtrue; then
 AC_DEFINE(HAVE_FAAD2)
 fi
 
+dnl
+dnl FLAC
+dnl
+
+OLD_CFLAGS=$CFLAGS
+OLD_LIBS=$LIBS
+ 
+LIBS="-lFLAC -lm"
+CFLAGS=""
+
+AH_TEMPLATE([HAVE_FLAC], [Enable FLAC])
+AC_MSG_CHECKING(for flac)
+have_flac="false"
+
+  AC_TRY_RUN([
+    #include <FLAC/stream_decoder.h>
+    #include <stdio.h>
+    main()
+    {
+    int version_major;
+    int version_minor;
+    int version_patchlevel;
+    fprintf(stderr, "FLAC__VERSION_STRING: %s\n", FLAC__VERSION_STRING);
+    if(sscanf(FLAC__VERSION_STRING, "%d.%d.%d", &version_major,
+              &version_minor, &version_patchlevel) < 3)
+      return -1;
+    if((version_major != 1) || (version_minor < 1))
+      return 1;
+    return 0;
+    }
+  ],
+  [
+    # program could be run
+    have_flac="true"
+    AC_MSG_RESULT(yes)
+    FLAC_CFLAGS=$CFLAGS
+    FLAC_LIBS=$LIBS
+
+  ],
+    # program could not be run
+    AC_MSG_RESULT(no)
+)
+
+CFLAGS=$OLD_CFLAGS
+LIBS=$OLD_LIBS
+
+AC_SUBST(FLAC_CFLAGS)
+AC_SUBST(FLAC_LIBS)
+
+AM_CONDITIONAL(HAVE_FLAC, test x$have_flac = xtrue)
+
+if test x$have_flac = xtrue; then
+AC_DEFINE(HAVE_FLAC)
+fi
+
+
 
 dnl
 dnl MAD
@@ -401,6 +457,14 @@ echo "Yes"
 else
 echo "Missing"
 fi
+
+echo -n "flac:              "
+if test "x$have_flac" = "xtrue"; then
+echo "Yes"
+else
+echo "Missing"
+fi
+
 
 echo -n "vorbis:            "
 if test "x$have_vorbis" = "xtrue"; then
